import Link from 'next/link';
import { ArrowRight, CheckCircle2 } from 'lucide-react';

export const metadata={title:'Hazır İş ve Satış Paketleri',description:'İlk satıştan otomasyona ve büyümeye kadar kullanıma hazır planları ve şablonları inceleyin.',alternates:{canonical:'https://aikagan.com.tr/urunler',languages:{'tr-TR':'https://aikagan.com.tr/urunler',en:'https://aikagan.com/products/'}}};
const packs=[
  {badge:'En kolay başlangıç',name:'İlk Satış Başlangıç Paketi',price:'29 USD',desc:'Karışık bir fikri, kime ne sattığı belli olan net bir teklife dönüştürün ve ilk gerçek satış denemenizi yapın.',items:['7 Günde İlk Satış eylem planı','Teklif çalışma sayfası','Müşteri itirazlarına yanıt metinleri','24 saatlik başlangıç listesi','Uygulama çalışma dosyası','Golden Delivery Başlangıç ZIP'],slug:'masterclass-starter'},
  {badge:'En çok önerilen',name:'Satış Dönüşümü Pro',price:'79 USD',desc:'Tekliften müşteri trafiğine, ödeme sayfasından takibe kadar bütün satış yolunu 30 günlük düzene bağlayın.',items:['3 satış hunisi modeli','5 düzenlenebilir teklif şablonu','Organik ve ücretli müşteri bulma denemeleri','30 günlük satış takvimi','6 otomasyon şablonu','Golden Delivery Pro ZIP'],slug:'masterclass-pro'},
  {badge:'Çalışan sistemi büyütmek için',name:'Ölçekleme ve Lisanslama Komutan Paketi',price:'149 USD',desc:'İşe yarayan satış düzeninizi tekrar edilebilir ve ölçülebilir bir sisteme çevirin.',items:['Ana işleyiş ve gelir haritası','Beyaz etiket kullanım rehberi','60 günlük büyüme planı','Ortaklık rehberi','Otomasyon hata önleme kontrolleri','KPI takip paneli'],slug:'masterclass-commander'},
];
export default function TurkishProducts(){return <main className="min-h-screen bg-[#08080a] px-5 py-20 text-white"><section className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="text-sm font-semibold text-emerald-300">KENDİN YAP PAKETLERİ</p><h1 className="mt-3 text-5xl font-black md:text-7xl">Hazır Paketler</h1><p className="mt-5 text-lg leading-8 text-neutral-300">İlk satış için Başlangıç, bütün satış yolu için Pro, çalışan sistemi büyütmek için Komutan paketini seçin.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{packs.map(p=><article key={p.slug} className="flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-7"><p className="text-sm font-bold text-amber-300">{p.badge}</p><h2 className="mt-3 text-2xl font-black">{p.name}</h2><p className="mt-3 text-3xl font-black text-amber-300">{p.price}</p><p className="mt-1 text-xs text-neutral-500">Tek seferlik ödeme · güvenli dijital teslimat</p><p className="mt-5 text-sm leading-7 text-neutral-300">{p.desc}</p><ul className="mt-6 space-y-3">{p.items.map(i=><li key={i} className="flex gap-2 text-sm text-neutral-300"><CheckCircle2 className="h-4 w-4 flex-none text-emerald-300"/>{i}</li>)}</ul><Link href={`/products/${p.slug}/?lang=tr`} className="mt-8 inline-flex items-center justify-center gap-2 rounded-xl bg-amber-300 px-5 py-3 font-black text-black">İçeriği ve koşulları gör <ArrowRight className="h-4 w-4"/></Link></article>)}</div><div className="mt-12 rounded-3xl border border-emerald-400/20 bg-emerald-400/[0.04] p-7"><h2 className="text-2xl font-bold">Nasıl çalışır?</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{[['1','Paketinizi seçin','İhtiyacınıza uygun çalışma derinliğini seçin.'],['2','Güvenli ödemeyi tamamlayın','Yalnızca doğrulanmış ürün ödeme sayfasına geçin.'],['3','Dosyalarınıza ulaşın','Ödeme onaylanınca güvenli teslimat başlasın.']].map(([n,t,b])=><div key={n}><span className="text-amber-300 font-black">{n}</span><h3 className="mt-2 font-bold">{t}</h3><p className="mt-2 text-sm text-neutral-400">{b}</p></div>)}</div></div></section></main>}
