import Link from 'next/link';
import { ArrowRight, CheckCircle2, Compass, FileCheck2, Gauge, Radar, ShieldCheck, Sparkles, Workflow } from 'lucide-react';

export const metadata = {
  title: 'Flight 002 — Teşhis Et, Uygula, Doğrula',
  description: 'AIKAGAN Flight 002, gerçek iş sorunlarını öncelikli uygulama görevlerine çevirir ve sonucu kanıt kapılarıyla doğrular.',
  alternates: { canonical: 'https://aikagan.com/tr/flight' },
};

const flow = [
  { step:'01', title:'Teşhis et', body:'Gerçek bir iş sıkıntısından başla: gelir kaçağı, düşük dönüşüm, teslimat yükü, dağınık operasyon veya doğrulanması gereken yeni bir fırsat.', icon:Radar },
  { step:'02', title:'Önceliklendir', body:'Beklenen değer, aciliyet, kanıt, efor ve riske göre gürültüyü tek bir öncelikli göreve indir.', icon:Compass },
  { step:'03', title:'Uygula', body:'Seçilen görevi net adımlara, sorumlulara, araçlara, onaylara, teslim kriterlerine ve ölçülebilir çıktılara dönüştür.', icon:Workflow },
  { step:'04', title:'Doğrula', body:'Üretilen işi tamamlanmış işten ayır. Ödeme, yayın, teslimat ve sonuç iddiaları ancak destekleyen kanıt varsa geçerli kabul edilir.', icon:FileCheck2 },
] as const;

const capabilities = [
  ['Teşhis', 'Sorunun nerede oluştuğunu, müşteriye ve gelire nasıl yansıdığını görünür hale getiririz.'],
  ['Öncelik', 'Değer, aciliyet, risk, efor ve bağımlılıkları karşılaştırarak önce yapılacak işi seçeriz.'],
  ['Uygulama', 'Araştırma, analiz, içerik, tasarım ve otomasyon yeteneklerini yalnızca seçilen sonuç için bir araya getiririz.'],
  ['Doğrulama', 'Teslimatı, kabul kriterlerini ve ticari sonucu kanıtla doğrular; test ile gerçek müşteri faaliyetini ayırırız.'],
] as const;

const releaseState = [
  ['Ücretsiz teşhis araçları', 'AÇIK'],
  ['Ücretsiz teslimat örneği', 'AÇIK'],
  ['Uygulama talepleri', 'AÇIK'],
  ['AutonomaX çalışma alanı', 'DOĞRULANIYOR'],
  ['Kendi kendine ücretli ödeme', 'KAPALI'],
] as const;

export default function TurkishFlightPage() {
  return <main className="min-h-screen bg-[#08080a] text-white">
    <section className="relative overflow-hidden border-b border-white/5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_24%,rgba(212,175,55,0.18),transparent_34%),radial-gradient(circle_at_14%_74%,rgba(16,185,129,0.10),transparent_32%),linear-gradient(145deg,#08080a_0%,#120e07_52%,#08080a_100%)]"/><div className="relative mx-auto grid min-h-[650px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_0.92fr] lg:py-28">
      <div><div className="inline-flex items-center gap-2 rounded-full border border-amber-300/25 bg-amber-300/[0.06] px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-amber-300"><span className="h-2 w-2 rounded-full bg-emerald-300"/>Flight 002 · ücretsiz giriş açık</div><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[0.95] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Sorunu teşhis et. <span className="text-amber-300">Doğru işi seç.</span> Sonucu doğrula.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-300">İşinizi platform isimleriyle uğraştırmadan, gerçek bir sorundan uygulanabilir bir göreve ilerletiyoruz. Önce neyin önemli olduğunu netleştirir, sonra gerekli uzmanlık ve üretim yeteneklerini yalnızca o sonuç için bir araya getiririz.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tr/tools/revenue-leak-scan" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black hover:bg-amber-200">Ücretsiz değerlendirme sonucunu alın <ArrowRight className="h-4 w-4"/></Link><Link href="/tr/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold hover:border-white/30">İhtiyacınızı dinleyelim</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-neutral-400">{['Uydurma ROI yok','Simüle hazırlık yok','Gelirden önce kanıt'].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300"/>{item}</span>)}</div></div>
      <div className="rounded-[32px] border border-white/10 bg-black/35 p-7 sm:p-9"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-neutral-500">Yayın kapısı</p><h2 className="mt-2 text-2xl font-black">Gerçekte ne açık?</h2></div><ShieldCheck className="h-8 w-8 text-emerald-300"/></div><div className="mt-6 space-y-3">{releaseState.map(([label,state])=><div key={label} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3.5"><span className="text-sm text-neutral-300">{label}</span><span className={state==='AÇIK'?'text-xs font-black text-emerald-300':'text-xs font-black text-amber-300'}>{state}</span></div>)}</div><p className="mt-5 text-sm leading-6 text-neutral-400">Ücretli ödeme; teklif → ödeme → kalite kontrol → teslimat → yeniden erişim → kabul zinciri baştan sona doğrulanana kadar kapalı kalır.</p></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm font-semibold text-emerald-300">ÇALIŞMA AKIŞI</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Sinyalden doğrulanmış sonuca dört kapı.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-4">{flow.map(({step,title,body,icon:Icon})=><article key={step} className="rounded-3xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-[0.2em] text-neutral-500">{step}</span><Icon className="h-6 w-6 text-amber-300"/></div><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{body}</p></article>)}</div></section>

    <section className="border-y border-white/5 bg-[#0b0b0e]"><div className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-start"><div><p className="text-sm font-semibold text-amber-300">İHTİYACA GÖRE DOĞRU YETENEKLER</p><h2 className="mt-3 text-4xl font-black">Tek sistem, ihtiyaca göre doğru çalışma biçimi.</h2><p className="mt-5 leading-8 text-neutral-400">Her iş aynı çözümü gerektirmez. Önce ihtiyacı değerlendirir, ardından gerekli analiz, araştırma, üretim ve otomasyon yeteneklerini seçerek uygulanabilir bir çalışma oluştururuz.</p></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{body}</p></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm font-semibold text-emerald-300">BAŞLANGIÇ YOLLARI</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Mimariden değil, istediğiniz sonuçtan başlayın.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">
      <Link href="/tr/tools/revenue-leak-scan" className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-7 hover:border-amber-300/40"><Gauge className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">GELİR ONARIMI</p><h3 className="mt-3 text-2xl font-black">Ticari darboğazı bulun</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">Ücretsiz değerlendirmeyi tamamlayın; teklif, güven, ödeme, teslimat, takip, ölçüm ve tekrar satıştaki zayıf halkaları sıralayın.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-black text-amber-300">Ücretsiz değerlendirme <ArrowRight className="h-4 w-4"/></span></Link>
      <Link href="/tr/contact" className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-7 hover:border-amber-300/40"><Sparkles className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">SİZE ÖZEL ÇALIŞMA</p><h3 className="mt-3 text-2xl font-black">İhtiyacınızı uygulanabilir göreve çevirin</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">Fikrinizi, operasyon sorununu veya geliştirmek istediğiniz alanı getirin. Uygulama taahhüdünden önce en değerli sonraki işi birlikte sınırlandıralım.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-black text-amber-300">İhtiyacınızı dinleyelim <ArrowRight className="h-4 w-4"/></span></Link>
      <div aria-disabled="true" className="flex flex-col rounded-3xl border border-white/10 bg-white/[0.02] p-7 opacity-80"><Workflow className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">AUTONOMAX ÇALIŞMA ALANI</p><h3 className="mt-3 text-2xl font-black">Uygulama alanı yeniden doğrulanıyor</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">Görev durumu, müşteri erişimi, teslimat ve geri dönüş yollarını uçtan uca doğrulamadan sizi çalışmayan bir alana göndermeyeceğiz.</p><span className="mt-7 text-sm font-black text-neutral-500">Yayın doğrulaması sürüyor</span></div>
    </div></section>

    <section className="px-6 pb-24"><div className="mx-auto max-w-5xl rounded-[32px] border border-amber-300/20 bg-[radial-gradient(circle_at_50%_0%,rgba(212,175,55,0.11),transparent_55%),#0d0d10] px-7 py-14 text-center sm:px-12"><FileCheck2 className="mx-auto h-8 w-8 text-amber-300"/><p className="mt-5 text-sm font-semibold text-amber-300">SONRAKİ ADIM</p><h2 className="mt-4 text-4xl font-black">Gerçek bir darboğaz getirin. Oradan başlayalım.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-neutral-400">Önce platform satın almanız veya iç mimariyi öğrenmeniz gerekmez. Sorunu görünür hale getirin; uygulamayı ancak değer ve kanıt desteklediğinde ilerletelim.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/tr/tools/revenue-leak-scan" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black hover:bg-amber-200">Ücretsiz değerlendirme <ArrowRight className="h-4 w-4"/></Link><Link href="/tr/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold hover:border-white/30">İhtiyacınızı dinleyelim</Link></div></div></section>
  </main>;
}
