import Link from 'next/link';
import { ArrowRight, CheckCircle2, Compass, FileCheck2, Gauge, Radar, ShieldCheck, Sparkles, Workflow } from 'lucide-react';

export const metadata = {
  title: 'Flight 002 — Diagnose, Execute, Verify',
  description: 'AIKAGAN Flight 002 turns real business friction into a ranked implementation mission and verifies the result with explicit evidence gates.',
  alternates: { canonical: 'https://aikagan.com/flight' },
};

const flow=[
  {step:'01',title:'Diagnose',body:'Start from observable business friction: revenue leakage, weak conversion, delivery burden, fragmented operations, or an opportunity that needs validation.',icon:Radar},
  {step:'02',title:'Rank',body:'Reduce noise to one prioritized mission using expected value, urgency, evidence, effort and risk.',icon:Compass},
  {step:'03',title:'Execute',body:'Turn the selected mission into scoped actions, owners, tools, approvals, handoffs, acceptance criteria and measurable outputs.',icon:Workflow},
  {step:'04',title:'Verify',body:'Separate generated work from operational truth. Payment, deployment, delivery and outcome claims only pass when supporting evidence exists.',icon:FileCheck2},
] as const;
const capabilities=[
  ['Diagnosis','Make the problem, its business impact and the affected customer path visible.'],
  ['Prioritization','Compare value, urgency, risk, effort and dependencies before committing resources.'],
  ['Implementation','Assemble research, analysis, production, design and automation only around the selected outcome.'],
  ['Verification','Check delivery, acceptance and commercial truth while keeping test activity separate from real customer evidence.'],
] as const;
const releaseState=[['Free diagnostics','LIVE'],['Free delivery sample','LIVE'],['Implementation requests','LIVE'],['AutonomaX workspace','VERIFYING'],['Self-serve paid checkout','GATED']] as const;

export default function FlightPage(){return <main className="min-h-screen bg-[#08080a] text-white">
<section className="relative overflow-hidden border-b border-white/5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_24%,rgba(212,175,55,0.18),transparent_34%),radial-gradient(circle_at_14%_74%,rgba(16,185,129,0.10),transparent_32%),linear-gradient(145deg,#08080a_0%,#120e07_52%,#08080a_100%)]"/><div className="relative mx-auto grid min-h-[650px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_0.92fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-amber-300/25 bg-amber-300/[0.06] px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-amber-300"><span className="h-2 w-2 rounded-full bg-emerald-300"/>Flight 002 · free entry live</div><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[0.95] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Diagnose the friction. <span className="text-amber-300">Choose the right work.</span> Verify the result.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-300">Start from a real business problem instead of learning our internal platform names. We clarify what matters, then assemble the required expertise and production capability around that outcome.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tools/revenue-leak-scan" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black hover:bg-amber-200">Get a free assessment <ArrowRight className="h-4 w-4"/></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold hover:border-white/30">Tell us what you need</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-neutral-400">{['No invented ROI','No simulated readiness','Evidence before monetization'].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300"/>{item}</span>)}</div></div><div className="rounded-[32px] border border-white/10 bg-black/35 p-7 sm:p-9"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-neutral-500">Release gate</p><h2 className="mt-2 text-2xl font-black">What is actually live?</h2></div><ShieldCheck className="h-8 w-8 text-emerald-300"/></div><div className="mt-6 space-y-3">{releaseState.map(([label,state])=><div key={label} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3.5"><span className="text-sm text-neutral-300">{label}</span><span className={state==='LIVE'?'text-xs font-black text-emerald-300':'text-xs font-black text-amber-300'}>{state}</span></div>)}</div><p className="mt-5 text-sm leading-6 text-neutral-400">Paid checkout stays gated until offer → payment → QA → delivery → re-access → acceptance is verified end to end.</p></div></div></section>
<section className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm font-semibold text-emerald-300">OPERATING PATH</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Four gates from signal to verified outcome.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-4">{flow.map(({step,title,body,icon:Icon})=><article key={step} className="rounded-3xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-[0.2em] text-neutral-500">{step}</span><Icon className="h-6 w-6 text-amber-300"/></div><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{body}</p></article>)}</div></section>
<section className="border-y border-white/5 bg-[#0b0b0e]"><div className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-start"><div><p className="text-sm font-semibold text-amber-300">RIGHT CAPABILITY FOR THE NEED</p><h2 className="mt-3 text-4xl font-black">One operating path, assembled around the outcome.</h2><p className="mt-5 leading-8 text-neutral-400">Not every problem needs the same solution. We assess the need first, then select the analysis, research, production and automation capabilities required to create a usable result.</p></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{body}</p></div>)}</div></div></div></section>
<section className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm font-semibold text-emerald-300">STARTING LANES</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Start from the outcome, not the architecture.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><Link href="/tools/revenue-leak-scan" className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-7 hover:border-amber-300/40"><Gauge className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">REVENUE REPAIR</p><h3 className="mt-3 text-2xl font-black">Find the commercial bottleneck</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">Assess offer, proof, checkout, fulfillment, follow-up, measurement and retention, then get a ranked improvement path.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-black text-amber-300">Free assessment <ArrowRight className="h-4 w-4"/></span></Link><Link href="/contact" className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-7 hover:border-amber-300/40"><Sparkles className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">TAILORED WORK</p><h3 className="mt-3 text-2xl font-black">Turn a need into an executable mission</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">Bring an idea, operating problem or improvement target. We bound the highest-value next work before implementation commitment.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-black text-amber-300">Tell us what you need <ArrowRight className="h-4 w-4"/></span></Link><div aria-disabled="true" className="flex flex-col rounded-3xl border border-white/10 bg-white/[0.02] p-7 opacity-80"><Workflow className="h-7 w-7 text-amber-300"/><p className="mt-6 text-xs font-black tracking-[0.22em] text-neutral-500">AUTONOMAX WORKSPACE</p><h3 className="mt-3 text-2xl font-black">Workspace release is being reverified</h3><p className="mt-3 flex-1 text-sm leading-7 text-neutral-400">We will not send you into an unreliable application until mission state, customer access, delivery and recovery paths pass end-to-end verification.</p><span className="mt-7 text-sm font-black text-neutral-500">Release verification in progress</span></div></div></section>
<section className="px-6 pb-24"><div className="mx-auto max-w-5xl rounded-[32px] border border-amber-300/20 bg-[#0d0d10] px-7 py-14 text-center"><FileCheck2 className="mx-auto h-8 w-8 text-amber-300"/><p className="mt-5 text-sm font-semibold text-amber-300">NEXT STEP</p><h2 className="mt-4 text-4xl font-black">Bring one real bottleneck. Start there.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-neutral-400">You do not need to buy a platform first. Make the problem visible, use the guidance yourself, or let us carry the implementation workload when the evidence justifies it.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/tools/revenue-leak-scan" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black">Free assessment <ArrowRight className="h-4 w-4"/></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold">Tell us what you need</Link></div></div></section>
</main>}
