import Link from 'next/link';
import { ArrowRight, CheckCircle2, Gauge, Gift, ShieldCheck, Sparkles, Workflow } from 'lucide-react';

export const metadata = {
  title: 'Ücretsiz Yapay Zekâ İş Araçları ve Pratik Otomasyon',
  description: 'İşinizde satışın nerede tıkandığını görün. Önce ücretsiz deneyin, sonucu görün, işinize yararsa devam edin.',
  alternates: { canonical: 'https://aikagan.com/tr', languages: { 'tr-TR': 'https://aikagan.com/tr', en: 'https://aikagan.com/' } },
};

const experiences = [
  { title:'Para nerede kaçıyor, bulun', body:'Yedi kolay soruyla teklif, güven, ödeme, teslimat, takip, ölçüm ve tekrar satış yolunuzu kontrol edin.', result:'Yönetici özeti, ilk üç öncelik ve uygulayabileceğiniz somut iyileştirme yönleri.', href:'/tr/tools/revenue-leak-scan/', cta:'Ücretsiz değerlendirme sonucunu alın', icon:Gauge, active:true },
  { title:'Hazır bir teslimat örneğini açın', body:'AIKAGAN teslimat yaklaşımının küçük bir Türkçe örneğini e-posta vermeden inceleyin.', result:'Satın almadan önce yaklaşımı ve size uygun olup olmadığını değerlendirin.', href:'/tr/free/golden-delivery-sample/', cta:'Ücretsiz örneği inceleyin', icon:Gift, active:true },
  { title:'AutonomaX çalışma alanı', body:'Görev, müşteri erişimi ve teslimat yollarını uçtan uca doğrulamadan sizi çalışmayan bir uygulamaya göndermiyoruz.', result:'Çalışma alanı doğrulandıktan sonra yeniden açılacak.', href:'', cta:'Yayın doğrulaması sürüyor', icon:Workflow, active:false },
] as const;

export default function TurkishHome() {
  return <main className="min-h-screen bg-[#08080a] text-white">
    <section className="relative overflow-hidden border-b border-white/5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_28%,rgba(212,175,55,0.16),transparent_34%),radial-gradient(circle_at_20%_72%,rgba(16,185,129,0.09),transparent_34%),linear-gradient(145deg,#08080a_0%,#110d06_55%,#08080a_100%)]"/><div className="relative mx-auto grid min-h-[690px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_0.92fr] lg:py-28">
      <div><p className="text-sm font-semibold text-emerald-300">GERÇEK İŞLER İÇİN PRATİK YAPAY ZEKÂ ARAÇLARI</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[0.96] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Önce ücretsiz deneyin. <span className="text-amber-300">İşinize yararsa devam edin.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-300">İşinizde satışın nerede tıkandığını görün, teklifinizi netleştirin ve tekrar eden işleri kolaylaştırın. Ücretsiz bir değerlendirmeyle başlayın; yalnızca gerçek ihtiyacınız varsa uygulamaya geçin.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tr/tools/revenue-leak-scan/" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black hover:bg-amber-200">Ücretsiz değerlendirme sonucunu alın <ArrowRight className="h-4 w-4"/></Link><Link href="/tr/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold hover:border-white/30">İhtiyacınızı dinleyelim</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-neutral-400">{['Kart gerekmez','Üyelik gerekmez','Sonuç hemen çıkar','Uydurma kazanç vaadi yok'].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300"/>{item}</span>)}</div></div>
      <div className="rounded-[32px] border border-white/10 bg-black/35 p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.28em] text-neutral-500">İlk değerlendirme yaklaşık 2 dakika sürer</p><div className="mt-6 space-y-4">{[['1','Size en yakın sorunu seçin','Satış mı yavaş? Teklif mi karışık? Size en yakın olanı seçin.'],['2','Sonucunuzu hemen görün','Kısa soruları yanıtlayın; puan, yönetici özeti ve önceliklerinizi alın.'],['3','Ne yapacağınıza siz karar verin','DIY adımları uygulayın, başka bir araç deneyin veya işi birlikte tamamlayalım.']].map(([n,t,b])=><div key={n} className="flex gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-full bg-amber-300 font-black text-black">{n}</span><div><h2 className="font-bold">{t}</h2><p className="mt-1 text-sm leading-6 text-neutral-400">{b}</p></div></div>)}</div></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-6 py-24"><p className="text-sm font-semibold text-emerald-300">Size en çok yardımcı olacak başlangıcı seçin</p><h2 className="mt-3 max-w-3xl text-4xl font-black sm:text-5xl">Değeri görmenin yolları.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-400">AIKAGAN’ı veya iç mimarisini bilmeniz gerekmiyor. Bugün neyi iyileştirmek istediğinizden başlayın.</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{experiences.map(({title,body,result,href,cta,icon:Icon,active})=>{const card=<><Icon className="h-7 w-7 text-amber-300"/><h3 className="mt-6 text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{body}</p><div className="mt-5 rounded-xl bg-black/25 p-4 text-sm text-neutral-300"><strong className="text-white">Elinizde ne kalır?</strong> {result}</div><span className={`mt-7 inline-flex items-center gap-2 text-sm font-bold ${active?'text-amber-300':'text-neutral-500'}`}>{cta} {active&&<ArrowRight className="h-4 w-4"/>}</span></>;return active?<Link key={title} href={href} className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-6 transition hover:-translate-y-1 hover:border-amber-300/40">{card}</Link>:<div key={title} aria-disabled="true" className="flex flex-col rounded-3xl border border-white/10 bg-white/[0.02] p-6 opacity-80">{card}</div>})}</div></section>

    <section className="border-y border-white/5 bg-[#0b0b0e]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold text-amber-300">Ücretsiz sonuç işinize yararsa ne olur?</p><h2 className="mt-3 text-4xl font-black">Ne kadar ilerleyeceğinize siz karar verin.</h2><p className="mt-5 leading-8 text-neutral-400">Yöntemi kendiniz uygulayın veya araştırma, tasarım, üretim, otomasyon ve kalite kontrol yükünü bize bırakın.</p><Link href="/tr/services/" className="mt-7 inline-flex items-center gap-2 rounded-xl border border-amber-300/35 px-5 py-3 font-bold text-amber-300">Uygulama desteğini inceleyin <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[['Ücretsiz','Değerlendirmeleri, örnekleri ve açık araçları ücretsiz kullanın.'],['Kendin Yap','Önerileri ve hazır kaynakları kendi işinize uygulayın.'],['Birlikte Kuralım','Belirli bir satış veya iş akışını sizin için tasarlayıp uygulayalım.'],['Birlikte Yürütelim','Kanıt oluştuğunda sistemi düzenli takip edip iyileştirelim.']].map(([t,b])=><div key={t} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><Sparkles className="h-5 w-5 text-amber-300"/><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{b}</p></div>)}</div></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-5xl rounded-[32px] border border-amber-300/20 bg-[#0d0d10] px-7 py-14 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-amber-300"/><p className="mt-5 text-sm font-semibold text-amber-300">Önce faydayı görün. Satın alma kararını sonra verin.</p><h2 className="mt-4 text-4xl font-black">Önce sorunu bulalım. Sonra gerçekten bir uygulamaya ihtiyacınız var mı, görelim.</h2><Link href="/tr/tools/revenue-leak-scan/" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black">Ücretsiz değerlendirme <ArrowRight className="h-4 w-4"/></Link></div></section>
  </main>;
}
