import Link from 'next/link';
import { ArrowRight, CheckCircle2, Gauge, Gift, ShieldCheck, Sparkles, Workflow } from 'lucide-react';

export const metadata = {
  title: 'Ücretsiz Yapay Zekâ İş Araçları ve Pratik Otomasyon',
  description: 'İşinizde satışın nerede tıkandığını görün. Önce ücretsiz deneyin, sonucu görün, işinize yararsa devam edin.',
  alternates: { canonical: 'https://aikagan.com/tr', languages: { 'tr-TR': 'https://aikagan.com/tr', en: 'https://aikagan.com/' } },
};

const experiences = [
  { title: 'Para nerede kaçıyor, bulun', body: 'Yedi kolay soruyla teklif, ödeme, teslimat, takip ve tekrar satış yolunuzu kontrol edin.', result: 'Önce düzeltmeniz gereken noktaların sıralı listesi.', href: '/tr/tools/revenue-leak-scan/', cta: 'Ücretsiz puanımı al', icon: Gauge },
  { title: 'Hazır bir teslimat örneğini açın', body: 'AIKAGAN teslimat yaklaşımının küçük bir Türkçe örneğini e-posta vermeden inceleyin.', result: 'Satın almadan önce yaklaşımı ve size uygun olup olmadığını değerlendirin.', href: '/tr/free/golden-delivery-sample/', cta: 'Ücretsiz örneği aç', icon: Gift },
  { title: 'AutonomaX nasıl çalışıyor, deneyin', body: 'Bir iş hedefinin nasıl küçük görevlere ve ölçülebilir ilerlemeye dönüştüğünü görün.', result: 'Ürünü uzun uzun okumak yerine kullanarak anlayın.', href: 'https://app.aikagan.com/autonomax/', cta: 'AutonomaX’ı keşfet', icon: Workflow },
];

export default function TurkishHome() {
  return <main className="min-h-screen bg-[#08080a] text-white">
    <section className="relative overflow-hidden border-b border-white/5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_28%,rgba(212,175,55,0.16),transparent_34%),radial-gradient(circle_at_20%_72%,rgba(16,185,129,0.09),transparent_34%),linear-gradient(145deg,#08080a_0%,#110d06_55%,#08080a_100%)]"/><div className="relative mx-auto grid min-h-[690px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.08fr_0.92fr] lg:py-28">
      <div><p className="text-sm font-semibold text-emerald-300">GERÇEK İŞLER İÇİN PRATİK YAPAY ZEKÂ ARAÇLARI</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[0.96] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Önce ücretsiz deneyin. <span className="text-amber-300">İşinize yararsa devam edin.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-neutral-300">İşinizde satışın nerede tıkandığını görün, teklifinizi netleştirin ve tekrar eden işleri kolaylaştırın. Ücretsiz bir araçla başlayın; sonucu hemen görün.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tr/tools/revenue-leak-scan/" className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black hover:bg-amber-200">Ücretsiz Gelir Kaçağı Testini Başlat <ArrowRight className="h-4 w-4"/></Link><Link href="/tr/tools/" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-6 py-3.5 text-sm font-bold hover:border-white/30">Tüm ücretsiz araçları gör</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-neutral-400">{['Kart gerekmez','Üyelik gerekmez','Sonuç hemen çıkar','Uydurma kazanç vaadi yok'].map(item=><span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300"/>{item}</span>)}</div></div>
      <div className="rounded-[32px] border border-white/10 bg-black/35 p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.28em] text-neutral-500">İlk deneme yaklaşık 2 dakika sürer</p><div className="mt-6 space-y-4">{[['1','Size en yakın sorunu seçin','Satış mı yavaş? Teklif mi karışık? Size en yakın olanı seçin.'],['2','Sonucunuzu hemen görün','Kısa soruları yanıtlayın ve size özel puanı alın.'],['3','Ne yapacağınıza siz karar verin','Sonucu kullanın, başka bir araç deneyin veya kurulumu birlikte yapalım.']].map(([n,t,b])=><div key={n} className="flex gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-full bg-amber-300 font-black text-black">{n}</span><div><h2 className="font-bold">{t}</h2><p className="mt-1 text-sm leading-6 text-neutral-400">{b}</p></div></div>)}</div><div className="mt-6 rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.05] p-5"><p className="text-sm font-semibold text-emerald-300">Nereden başlayacağınızı bilmiyor musunuz?</p><p className="mt-2 text-sm leading-6 text-neutral-300">Gelir Kaçağı Testi ücretsizdir, üyelik istemez ve önce neyi düzeltmeniz gerektiğini gösterir.</p></div></div>
    </div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><p className="text-sm font-semibold text-emerald-300">Size en çok yardımcı olacak başlangıcı seçin</p><h2 className="mt-3 max-w-3xl text-4xl font-black sm:text-5xl">Değeri görmenin üç ücretsiz yolu.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-400">AIKAGAN’ı veya yapay zekâ sistemlerini önceden bilmeniz gerekmiyor. Bugün neyi iyileştirmek istediğinizi seçin.</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{experiences.map(({title,body,result,href,cta,icon:Icon})=><Link key={title} href={href} className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-6 transition hover:-translate-y-1 hover:border-amber-300/40"><Icon className="h-7 w-7 text-amber-300"/><h3 className="mt-6 text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{body}</p><div className="mt-5 rounded-xl bg-black/25 p-4 text-sm text-neutral-300"><strong className="text-white">Elinizde ne kalır?</strong> {result}</div><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-amber-300">{cta} <ArrowRight className="h-4 w-4"/></span></Link>)}</div></section>
    <section className="border-y border-white/5 bg-[#0b0b0e]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold text-amber-300">Ücretsiz sonuç işinize yararsa ne olur?</p><h2 className="mt-3 text-4xl font-black">Ne kadar ilerleyeceğinize siz karar verin.</h2><p className="mt-5 leading-8 text-neutral-400">Sonucu ücretsiz kullanın, hazır bir paket seçin veya kurulumu bize bırakın. Yükseltme zorunluluğu yok.</p><Link href="/tr/services/" className="mt-7 inline-flex items-center gap-2 rounded-xl border border-amber-300/35 px-5 py-3 font-bold text-amber-300">Uygulama desteğini gör <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[['Ücretsiz','Testleri, örnekleri ve açık araçları ücretsiz kullanın.'],['Kendin Yap','Hazır şablonları ve paketleri kendi işinize uyarlayın.'],['Birlikte Kuralım','Belirli bir satış veya iş akışını sizin için kuralım.'],['Birlikte Yürütelim','Sisteminizi düzenli takip edip iyileştirelim.']].map(([t,b])=><div key={t} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><Sparkles className="h-5 w-5 text-amber-300"/><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-neutral-400">{b}</p></div>)}</div></div></section>
    <section className="px-6 py-24"><div className="mx-auto max-w-5xl rounded-[32px] border border-amber-300/20 bg-[#0d0d10] px-7 py-14 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-amber-300"/><p className="mt-5 text-sm font-semibold text-amber-300">Önce faydayı görün. Satın alma kararını sonra verin.</p><h2 className="mt-4 text-4xl font-black">Önce sorunu bulalım. Sonra gerçekten bir çözüme ihtiyacınız var mı, görelim.</h2><Link href="/tr/tools/revenue-leak-scan/" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 text-sm font-black text-black">Ücretsiz teste başla <ArrowRight className="h-4 w-4"/></Link></div></section>
  </main>;
}
