import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { getProduct } from "@/lib/products";
import path from "path";
import fs from "fs";

// ─────────────────────────────────────────────────────────────────────────────
// Secure Download Route
//
// Validates a signed download token generated by the LemonSqueezy webhook,
// resolves the product ZIP path, and streams the file to the buyer.
//
// Tokens are self-contained HMAC-signed payloads:
//   <base64url(JSON)>.<base64url(HMAC-SHA256)>
//
// The private/ directory is NOT served by Next.js static file serving —
// only this API route can deliver its contents.
// ─────────────────────────────────────────────────────────────────────────────

const TOKEN_SECRET = process.env.DOWNLOAD_TOKEN_SECRET ?? "";

interface TokenPayload {
  slug: string;
  orderId: string;
  email: string;
  exp: number;
}

function verifyAndDecodeToken(token: string): TokenPayload | null {
  if (!TOKEN_SECRET) return null;
  const parts = token.split(".");
  if (parts.length !== 2) return null;
  const [payloadB64, sig] = parts;
  const expectedSig = crypto
    .createHmac("sha256", TOKEN_SECRET)
    .update(payloadB64)
    .digest("base64url");
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null;
  try {
    const payload: TokenPayload = JSON.parse(Buffer.from(payloadB64, "base64url").toString());
    if (Date.now() > payload.exp) return null;
    return payload;
  } catch {
    return null;
  }
}

export async function GET(
  _req: NextRequest,
  { params }: { params: { token: string } }
) {
  const payload = verifyAndDecodeToken(params.token);

  if (!payload) {
    return NextResponse.json(
      { error: "Invalid or expired download link. Contact support at lazylarries@gmail.com" },
      { status: 403 }
    );
  }

  const product = getProduct(payload.slug);
  if (!product || !product.zipFilename) {
    return NextResponse.json({ error: "Product not found" }, { status: 404 });
  }

  // ZIPs live in /private/downloads/ — not publicly accessible
  const filePath = path.join(process.cwd(), "private", "downloads", product.zipFilename);

  if (!fs.existsSync(filePath)) {
    console.error(`[download] File missing: ${filePath}`);
    return NextResponse.json(
      { error: "Download file not found. Please contact support." },
      { status: 404 }
    );
  }

  const fileBuffer = fs.readFileSync(filePath);
  const filename = product.zipFilename;

  console.log(JSON.stringify({
    event: "download_served",
    slug: payload.slug,
    orderId: payload.orderId,
    filename,
    timestamp: new Date().toISOString(),
  }));

  return new NextResponse(fileBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(fileBuffer.length),
      "Cache-Control": "no-store, no-cache",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
