import { NextRequest, NextResponse } from "next/server";
import { CHECKOUT_SENTINEL, getProduct } from "@/lib/products";
import { recordIntent, type IntentRecord } from "@/lib/income-ledger";
import { getPaddleClient } from "@/lib/paddle-client";
import { tokenStore } from "@/lib/token-store";
import { rateLimit, clientKey, rateLimitResponse } from "@/lib/rate-limit";
import { resolveCouponPrice } from "@/lib/coupons";
import { getGumroadProduct } from "@/lib/gumroad-products";
import { isGumroadApiConfigured } from "@/lib/gumroad-api";
import { ShopierPaymentFlow } from "@nopeion/shopier";
import { canonicalSiteOrigin, isFirstPartyCommerceHost, paddleCheckoutOrigin } from "@/lib/site-origin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface CheckoutBody { slug:string; ref?:string|null; provider?:string|null; utm_source?:string|null; utm_medium?:string|null; utm_campaign?:string|null; utm_term?:string|null; utm_content?:string|null; country?:string|null; email?:string|null; sessionId?:string|null; coupon?:string|null; }
type CheckoutResult = { provider:"paddle"|"lemonsqueezy"|"gumroad"|"shopier"; url:string; transactionId:string|null; };
const STOREFRONT_MAINTENANCE = true;
function newSessionId(){return `${Date.now().toString(36)}.${Math.random().toString(36).slice(2,10)}`;}
function manualFallbackUrl(req:NextRequest,slug:string,intentId:string){const url=new URL("/checkout/manual",canonicalSiteOrigin(req.nextUrl.origin));url.searchParams.set("slug",slug);url.searchParams.set("intent",intentId);return url.toString();}
function lemonMerchantApproved(){return process.env.LEMONSQUEEZY_MERCHANT_APPROVED==="true"&&process.env.LEMONSQUEEZY_CHECKOUT_ENABLED==="true";}
const CATALOG_PRICE_IDS:Record<string,string>={"masterclass-starter":"pri_01kx0rg4hmnpbdpsnx3d7j8h5q","masterclass-pro":"pri_01kx0rg4q1ed110tw5cc4xqfs3","masterclass-commander":"pri_01kx0rg4w962z7vmn53c8pq7n3"};

async function tryPaddle(req:NextRequest,body:CheckoutBody,intent:IntentRecord,requestHostname:string):Promise<CheckoutResult|null>{
 if(process.env.PADDLE_CHECKOUT_DISABLED==="true"||!isFirstPartyCommerceHost(requestHostname))return null;
 const paddle=getPaddleClient();const product=getProduct(body.slug);if(!paddle||!product?.price||product.checkoutUrl!==CHECKOUT_SENTINEL)return null;
 try{const priceInfo=resolveCouponPrice(body.slug,body.coupon);const customData:Record<string,string>={product_slug:body.slug,ref_code:body.ref??"",utm_source:body.utm_source??"",utm_medium:body.utm_medium??"",utm_campaign:body.utm_campaign??"",...(priceInfo.applied?{coupon:body.coupon??"",test_price:"1"}:{})};const priceId=CATALOG_PRICE_IDS[body.slug];const transaction=priceInfo.applied||!priceId?await paddle.transactions.create({items:[{quantity:1,price:{description:product.description,name:`${product.tier} — ${product.name}${priceInfo.applied?" (TEST $1)":""}`,unitPrice:{amount:String(priceInfo.effectivePriceCents),currencyCode:"USD"},product:{name:`${product.tier} — ${product.name}${priceInfo.applied?" (TEST $1)":""}`,taxCategory:"saas",description:product.description}}}],customData}):await paddle.transactions.create({items:[{quantity:1,priceId}],customData});if(transaction.id)await tokenStore.set(transaction.id,{token:null,slug:body.slug,email:body.email??null,exp:Date.now()+48*60*60*1000});return{provider:"paddle",url:transaction.id?new URL(`/checkout?_ptxn=${encodeURIComponent(transaction.id)}`,paddleCheckoutOrigin()).toString():manualFallbackUrl(req,body.slug,String(intent.capturedAt)),transactionId:transaction.id};}catch(error){console.error("[income-checkout] Paddle failed",String(error));return null;}}

async function tryLemonSqueezy(req:NextRequest,body:CheckoutBody,intent:IntentRecord):Promise<CheckoutResult|null>{if(!lemonMerchantApproved())return null;const apiKey=process.env.LEMONSQUEEZY_API_KEY,storeId=process.env.LEMONSQUEEZY_STORE_ID,variantId=process.env[`LEMONSQUEEZY_VARIANT_${body.slug.replace(/-/g,"_").toUpperCase()}`];if(!apiKey||!storeId||!variantId)return null;try{const siteUrl=canonicalSiteOrigin(req.nextUrl.origin);const response=await fetch("https://api.lemonsqueezy.com/v1/checkouts",{method:"POST",headers:{Accept:"application/vnd.api+json","Content-Type":"application/vnd.api+json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({data:{type:"checkouts",attributes:{checkout_options:{embed:false,media:false,logo:true},checkout_data:{custom:{product_slug:body.slug,ref_code:body.ref??"",utm_source:body.utm_source??"",utm_medium:body.utm_medium??"",utm_campaign:body.utm_campaign??""}},product_options:{redirect_url:`${siteUrl}/checkout-success?provider=lemonsqueezy&ref=${encodeURIComponent(body.ref??"")}`,receipt_button_text:"Open your AIKAGAN delivery",receipt_thank_you_note:"Thank you — your verified delivery and workspace access are being prepared."}},relationships:{store:{data:{type:"stores",id:storeId}},variant:{data:{type:"variants",id:variantId}}}}}),signal:AbortSignal.timeout(15000)});const output=await response.json().catch(()=>null);if(!response.ok){console.error("[income-checkout] Lemon Squeezy rejected checkout",response.status);return null;}const id=output?.data?.id??null;if(id)await tokenStore.set(`ls:${id}`,{token:null,slug:body.slug,email:body.email??null,exp:Date.now()+48*60*60*1000});return{provider:"lemonsqueezy",url:output?.data?.attributes?.url??manualFallbackUrl(req,body.slug,String(intent.capturedAt)),transactionId:id};}catch(error){console.error("[income-checkout] Lemon Squeezy failed",String(error));return null;}}

function tryGumroad(body:CheckoutBody):CheckoutResult|null{const p=getGumroadProduct(body.slug);if(!p||!isGumroadApiConfigured())return null;try{const url=new URL(p.url);if(body.ref)url.searchParams.set("ref",body.ref);if(body.coupon)url.searchParams.set("coupon",body.coupon);return{provider:"gumroad",url:url.toString(),transactionId:p.id};}catch(error){console.error("[income-checkout] Gumroad URL preparation failed",String(error));return null;}}
async function getUsdToTryRate():Promise<number|null>{try{const response=await fetch("https://open.er-api.com/v6/latest/USD",{signal:AbortSignal.timeout(5000),cache:"no-store"});if(!response.ok)return null;const data=await response.json();const rate=data.rates?.TRY;return typeof rate==="number"&&Number.isFinite(rate)&&rate>0?rate:null;}catch(error){console.error("[currency-converter] Failed",error);return null;}}
function getProductImageUrl(slug:string){if(slug.includes("starter"))return"https://aikagan.com/thumb-starter.png";if(slug.includes("pro"))return"https://aikagan.com/thumb-pro.png";if(slug.includes("commander"))return"https://aikagan.com/thumb-commander.png";return"https://aikagan.com/og.png";}
async function tryShopier(body:CheckoutBody):Promise<CheckoutResult|null>{const pat=process.env.SHOPIER_PAT||process.env.AUTONOMAX_SHOPIER_PAT;const product=getProduct(body.slug);if(!product||product.checkoutUrl!==CHECKOUT_SENTINEL)return null;if(pat&&product.price){try{const usdRate=await getUsdToTryRate();if(usdRate!==null){const platformOrderId=`sp_${Date.now()}_${Math.floor(1000+Math.random()*9000)}`;await tokenStore.set(platformOrderId,{token:null,slug:body.slug,email:body.email??null,exp:Date.now()+48*60*60*1000});const result=await new ShopierPaymentFlow({api:{pat}}).create({title:product.name,amount:Math.round(product.price*usdRate),currency:"TRY",orderId:platformOrderId,imageUrl:getProductImageUrl(body.slug)});if(result?.paymentUrl)return{provider:"shopier",url:result.paymentUrl,transactionId:platformOrderId};}}catch(error){console.error("[income-checkout] Shopier API creation failed",String(error));}}const suffix=body.slug.replace(/-/g,"_").toUpperCase();const hostedUrl=process.env[`SHOPIER_PRODUCT_URL_${suffix}`]||process.env[`AUTONOMAX_SHOPIER_PRODUCT_URL_${suffix}`];return hostedUrl?{provider:"shopier",url:hostedUrl,transactionId:`sp-hosted-${Date.now()}`}:null;}

async function createCheckoutSession(req:NextRequest,body:CheckoutBody):Promise<{status:number;data:Record<string,unknown>}>{
 const product=getProduct(body.slug);if(!product)return{status:404,data:{error:`Unknown product: ${body.slug}`}};if(!product.price||product.priceModel==="free")return{status:400,data:{error:"Free products do not need checkout"}};if(product.checkoutUrl!==CHECKOUT_SENTINEL)return{status:409,data:{ok:false,error:"checkout_not_enabled_for_offer",detail:"This offer requires scope and delivery confirmation before payment.",requestUrl:product.checkoutUrl&&product.checkoutUrl.startsWith("/")?product.checkoutUrl:`/contact?product=${encodeURIComponent(body.slug)}`}};
 if(STOREFRONT_MAINTENANCE)return{status:503,data:{ok:false,error:"storefront_maintenance",detail:"Paid checkout is temporarily paused while product contents, licensing, payment, and delivery are verified end to end.",requestUrl:"/products"}};
 const sessionId=body.sessionId||newSessionId();const intent:IntentRecord={slug:body.slug,price:product.price,capturedAt:Date.now(),utm:{...(body.utm_source?{utm_source:body.utm_source}:{}),...(body.utm_medium?{utm_medium:body.utm_medium}:{}),...(body.utm_campaign?{utm_campaign:body.utm_campaign}:{}),...(body.utm_term?{utm_term:body.utm_term}:{}),...(body.utm_content?{utm_content:body.utm_content}:{})},ref:body.ref??null,source:"income_checkout"};let intentRecorded=false;try{await recordIntent(intent,sessionId);intentRecorded=true;}catch(error){console.warn("[income-checkout] intent evidence unavailable",String(error));}
 const hostname=(req.headers.get("host")||"").split(":")[0].toLowerCase();let result:CheckoutResult|null=null;
 if(body.provider==="paddle")result=await tryPaddle(req,body,intent,hostname);else if(body.provider==="gumroad")result=tryGumroad(body);else if(body.provider==="shopier")result=await tryShopier(body);else if(body.provider==="lemonsqueezy")result=await tryLemonSqueezy(req,body,intent);else{
   // Default buyers to the proven hosted Gumroad rail. Paddle remains available
   // explicitly and as a fallback, but no longer blocks purchases when its
   // overlay/domain/account state rejects an otherwise valid transaction.
   result=tryGumroad(body);
   if(!result)result=await tryShopier(body);
   if(!result)result=await tryPaddle(req,body,intent,hostname);
   if(!result)result=await tryLemonSqueezy(req,body,intent);
 }
 if(result)return{status:200,data:{ok:true,...result,intentId:sessionId,intent:{recorded:intentRecorded,at:new Date(intent.capturedAt).toISOString()}}};return{status:503,data:{ok:false,error:"checkout_unavailable",provider:null,detail:"No verified payment and fulfillment rail is currently available for this product.",manualUrl:manualFallbackUrl(req,body.slug,sessionId),intentId:sessionId,intent:{recorded:intentRecorded,at:new Date(intent.capturedAt).toISOString()}}};}

export async function POST(req:NextRequest){const limit=rateLimit({key:clientKey(req,"income-checkout"),max:30,windowMs:60000});if(!limit.allowed)return rateLimitResponse(limit);const body=(await req.json().catch(()=>null))as CheckoutBody|null;if(!body?.slug)return NextResponse.json({error:"slug required"},{status:400});const result=await createCheckoutSession(req,body);return NextResponse.json(result.data,{status:result.status});}
export async function GET(req:NextRequest){const slug=req.nextUrl.searchParams.get("slug");if(slug){const body:CheckoutBody={slug,ref:req.nextUrl.searchParams.get("ref"),provider:req.nextUrl.searchParams.get("provider"),utm_source:req.nextUrl.searchParams.get("utm_source"),utm_medium:req.nextUrl.searchParams.get("utm_medium"),utm_campaign:req.nextUrl.searchParams.get("utm_campaign"),utm_term:req.nextUrl.searchParams.get("utm_term"),utm_content:req.nextUrl.searchParams.get("utm_content"),country:req.nextUrl.searchParams.get("country"),email:req.nextUrl.searchParams.get("email"),sessionId:req.nextUrl.searchParams.get("sessionId")||req.nextUrl.searchParams.get("session_id"),coupon:req.nextUrl.searchParams.get("coupon")};const result=await createCheckoutSession(req,body);const url=typeof result.data.url==="string"?result.data.url:null;if(url)return NextResponse.redirect(url,303);return NextResponse.json(result.data,{status:result.status});}const hostname=(req.headers.get("host")||"").split(":")[0].toLowerCase();return NextResponse.json({ok:true,storefrontMode:STOREFRONT_MAINTENANCE?"maintenance":"open",commerceHost:hostname,firstPartyCommerceHost:isFirstPartyCommerceHost(hostname),defaultProvider:isGumroadApiConfigured()?"gumroad":"fallback",paddleCheckoutOrigin:paddleCheckoutOrigin(),providers:{paddle:Boolean(process.env.PADDLE_CHECKOUT_DISABLED!=="true"&&process.env.PADDLE_API_KEY&&process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN&&process.env.PADDLE_WEBHOOK_SECRET),gumroad:isGumroadApiConfigured(),shopier:Boolean(process.env.SHOPIER_PAT||process.env.AUTONOMAX_SHOPIER_PAT),lemonsqueezy:Boolean(lemonMerchantApproved()&&process.env.LEMONSQUEEZY_API_KEY&&process.env.LEMONSQUEEZY_STORE_ID&&process.env.LEMONSQUEEZY_WEBHOOK_SECRET)}});}
