import Link from 'next/link';
import { ArrowRight, Gauge, Gift, Workflow } from 'lucide-react';

export const metadata = { title: 'Ücretsiz İş Araçları — Satış, Teslimat ve Hedef', description: 'Kart veya üyelik gerektirmeden gelir kaybı testi yapın, teslimat örneğini inceleyin veya iş hedefinizi uygulanabilir bir taslağa dönüştürün.', alternates: { canonical: 'https://aikagan.com/tr/tools', languages: { 'tr-TR': 'https://aikagan.com/tr/tools', en: 'https://aikagan.com/tools' } } };

const tools = [
  { title:'Gelir Kaybı Testi', q:'Müşteriler neden satın almıyor?', body:'Teklif, güven, ödeme, teslimat, takip ve tekrar satış hakkında yedi kolay soruyu yanıtlayın.', result:'Hemen bir puan ve önce neyi düzeltmeniz gerektiğini gösteren sıralı liste.', href:'/tr/tools/revenue-leak-scan/', icon:Gauge, cta:'Ücretsiz puanımı al' },
  { title:'Ücretsiz Teslimat Örneği', q:'Nasıl bir dosya alacağım?', body:'Size nasıl bir dosya vereceğimizi Türkçe bir örnekle görün. E-posta adresi gerekmez.', result:'Para ödemeden önce örneğe bakın. Size uygun mu, karar verin.', href:'/tr/free/golden-delivery-sample/', icon:Gift, cta:'Ücretsiz örneği aç' },
  { title:'İş Hedefi Taslağı', q:'Yapmak istediğim işe nereden başlayayım?', body:'Ne yapmak istediğinizi, nelerin değişmemesi gerektiğini ve işle kimin ilgileneceğini yazın.', result:'Değiştirebileceğiniz bir plan ve nereden başlayabileceğinize dair öneri.', href:'/tr/outcome/intake/', icon:Workflow, cta:'Ücretsiz taslak hazırla' },
];

export default function TurkishTools(){return <main className="min-h-screen bg-[#08080a] px-5 py-20 text-white"><section className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-emerald-300">AIKAGAN’ı ücretsiz deneyin</p><h1 className="mt-3 text-5xl font-extrabold md:text-7xl">Çözmek istediğiniz sorunla başlayın.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-300">Bir araç seçin. Kısa soruları yanıtlayın ve sonucu görün.</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{tools.map(({title,q,body,result,href,icon:Icon,cta})=><Link key={title} href={href} className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-6 hover:border-amber-300/40"><Icon className="h-7 w-7 text-amber-300"/><p className="mt-6 text-sm font-semibold text-emerald-300">{q}</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-400">{body}</p><div className="mt-5 rounded-xl bg-black/25 p-4 text-sm text-neutral-300"><strong className="text-white">Alacağınız sonuç:</strong> {result}</div><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-amber-300">{cta} <ArrowRight className="h-4 w-4"/></span></Link>)}</div></section></main>}
