import Link from 'next/link';
import { ArrowRight, Gauge, Gift, Workflow } from 'lucide-react';

export const metadata = { title: 'Ücretsiz İş Araçları', description: 'Sorununuzu seçin ve hemen kullanabileceğiniz ücretsiz bir sonuç alın.', alternates: { canonical: 'https://aikagan.com/tr/tools' } };

const tools = [
  { title:'Gelir Kaçağı Testi', q:'İşim nerede hız kaybediyor?', body:'Teklif, güven, ödeme, teslimat, takip ve tekrar satış hakkında yedi kolay soruyu yanıtlayın.', result:'Hemen bir puan ve önce neyi düzeltmeniz gerektiğini gösteren sıralı liste.', href:'/tr/tools/revenue-leak-scan/', icon:Gauge, cta:'Ücretsiz puanımı al' },
  { title:'Ücretsiz Teslimat Örneği', q:'Hazır bir AIKAGAN teslimatı nasıl görünüyor?', body:'Teslimatlarda kullanılan kontrol yaklaşımının küçük bir Türkçe örneğini e-posta vermeden inceleyin.', result:'Para ödemeden önce yaklaşımı ve size uygun olup olmadığını değerlendirin.', href:'/tr/free/golden-delivery-sample/', icon:Gift, cta:'Ücretsiz örneği aç' },
  { title:'AutonomaX Gezgini', q:'Yapay zekâ bir iş hedefini nasıl eyleme çevirir?', body:'Bir hedefin nasıl görev, sonraki adım ve ölçülebilir ilerlemeye dönüştüğünü görün.', result:'Platformu özellik listesi okuyarak değil, deneyerek anlayın.', href:'https://app.aikagan.com/autonomax/', icon:Workflow, cta:'AutonomaX’ı keşfet' },
];

export default function TurkishTools(){return <main className="min-h-screen bg-[#08080a] px-5 py-20 text-white"><section className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-emerald-300">AIKAGAN’ı ücretsiz deneyin</p><h1 className="mt-3 text-5xl font-extrabold md:text-7xl">Çözmek istediğiniz sorunla başlayın.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-300">Platformu öğrenmeniz gerekmiyor. Bir araç seçin ve işe yarayan bir sonuç alın.</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{tools.map(({title,q,body,result,href,icon:Icon,cta})=><Link key={title} href={href} className="group flex flex-col rounded-3xl border border-white/10 bg-white/[0.03] p-6 hover:border-amber-300/40"><Icon className="h-7 w-7 text-amber-300"/><p className="mt-6 text-sm font-semibold text-emerald-300">{q}</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-400">{body}</p><div className="mt-5 rounded-xl bg-black/25 p-4 text-sm text-neutral-300"><strong className="text-white">Alacağınız sonuç:</strong> {result}</div><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-amber-300">{cta} <ArrowRight className="h-4 w-4"/></span></Link>)}</div></section></main>}
