// ─────────────────────────────────────────────────────────────────────────────
// PRODUCT CATALOG — AIKAGAN × AutonomaX
// Revenue rule: only offers with a verified automated fulfillment path may use
// managed checkout. Human/custom work remains an intake/request flow.
// ─────────────────────────────────────────────────────────────────────────────
export type ProductTier = "lead_magnet" | "tripwire" | "core" | "premium" | "masterclass" | "recurring";
export interface Product { slug:string; name:string; tier:string; ladderTier:ProductTier; price:number; originalPrice?:number; priceModel:"free"|"one_time"|"monthly"; description:string; bullets:string[]; checkoutUrl:string|null; zipFilename:string|null; nextSlug:string|null; badge?:string; guarantee?:string; image?:string; accentColor?:string; leadMagnetPath?:string; deliveryMode?:"download"|"service"|"hybrid"; deliverySteps?:string[]; positioning?:string; fulfillmentWindow?:string; }
export const CHECKOUT_SENTINEL = "paddle";
export const products: Product[] = [
{slug:"weekly-operating-map",name:"Weekly Operating Map",tier:"Free Download",ladderTier:"lead_magnet",price:0,priceModel:"free",description:"One-page weekly routine that replaces tool clutter with a single Sunday + Wednesday cadence.",bullets:["Sunday planning block (20 min)","Wednesday reset check-in (10 min)","Single-page printable PDF","Works offline, no tools required"],checkoutUrl:null,zipFilename:null,nextSlug:"masterclass-starter",leadMagnetPath:"/free-assets/weekly-operating-map.pdf",badge:"Free",accentColor:"#34d399"},
{slug:"builder-starter-checklist",name:"Builder Starter Checklist",tier:"Free Download",ladderTier:"lead_magnet",price:0,priceModel:"free",description:"10-step checklist for first-time builders: from idea to first sale, no overwhelm.",bullets:["10 sequential steps from idea to first paid validation","No paid ads required to use the checklist","Removes 'where do I even start' paralysis","Instant digital delivery"],checkoutUrl:null,zipFilename:null,nextSlug:"masterclass-starter",leadMagnetPath:"/free-assets/builder-starter-checklist.pdf",badge:"Free",accentColor:"#34d399"},
{slug:"golden-delivery-sample",name:"Golden Delivery — Sample Kit",tier:"Free Gift",ladderTier:"lead_magnet",price:0,priceModel:"free",description:"Curated extract from the full Golden Delivery system: a launch blueprint preview, one offer template, and a 24-hour activation checklist.",bullets:["7-Day First Sale Blueprint preview chapter","1 ready-to-use offer template","24-Hour Quick Win activation checklist","AutonomaX revenue map (1-page)","Email delivery — no card required"],checkoutUrl:null,zipFilename:"AutonomaX_Golden_Delivery_Starter_Pack.zip",nextSlug:"masterclass-starter",leadMagnetPath:"/free-assets/golden-delivery-sample-kit.pdf",badge:"Free Gift",accentColor:"#34d399"},
{slug:"ai-venture-launch-blueprint",name:"AI Venture Launch Blueprint",tier:"AutonomaX ProfitOS",ladderTier:"core",price:99,originalPrice:299,priceModel:"one_time",description:"Structured venture analysis for an idea, niche, or dormant project: market opportunity, monetization path, business model, execution roadmap, risk notes, and automation opportunities.",bullets:["Executive summary and market opportunity snapshot","Competitor and positioning analysis","Monetization strategy and business model map","14-day and 30-day execution roadmap","Operational risk and assumption notes","Automation opportunities for workflows and APIs","Implementation options scoped separately after review"],checkoutUrl:"/contact?product=ai-venture-launch-blueprint",zipFilename:null,nextSlug:"masterclass-pro",badge:"Request scope",accentColor:"#38bdf8",deliveryMode:"service",fulfillmentWindow:"Scope and delivery window confirmed before payment",positioning:"A scoped analysis service; it is not placed into automated checkout until delivery terms are confirmed.",deliverySteps:["Submit your idea, niche, and project context.","Receive confirmation of scope, deliverables, timing, and commercial terms.","Proceed only after the delivery commitment is explicit.","Completed work is delivered with a recommended next implementation action."]},
{slug:"masterclass-starter",name:"First-Sale Starter",tier:"AutonomaX Masterclass",ladderTier:"masterclass",price:29,originalPrice:97,priceModel:"one_time",description:"Turn a vague idea into one sellable offer and a concrete first-sale action sequence without building another complex stack.",bullets:["7-Day First-Sale action blueprint","Offer worksheet that forces a clear buyer, pain, promise, price, and CTA","Buyer-objection response scripts for real conversations","24-Hour activation checklist for the first outreach/conversion attempt","Execution workbook to track actions and evidence","Golden Delivery Starter Pack ZIP"],checkoutUrl:CHECKOUT_SENTINEL,zipFilename:"AutonomaX_Masterclass_Starter_Pack_v2.zip",nextSlug:"masterclass-pro",badge:"Fastest starting point",guarantee:"30-day money-back guarantee",accentColor:"#f59e0b",deliveryMode:"download",positioning:"Best when the immediate problem is getting from idea/tool clutter to a concrete offer and first selling motion."},
{slug:"masterclass-pro",name:"Revenue Conversion Pro",tier:"AutonomaX Masterclass",ladderTier:"masterclass",price:79,originalPrice:297,priceModel:"one_time",description:"Build the complete path from offer to traffic to checkout: positioning, funnel architecture, acquisition experiments, automation workflows, and a 30-day revenue operating cadence.",bullets:["3 funnel architectures with selection guidance","5 editable offer frameworks for clearer value propositions","Traffic playbook for organic and paid experiments","30-Day Revenue Operations Calendar","6 automation workflow templates to remove repetitive handoffs","AI implementation prompts for faster execution","Golden Delivery Pro Pack ZIP"],checkoutUrl:CHECKOUT_SENTINEL,zipFilename:"AutonomaX_Masterclass_Pro_Pack_v2.zip",nextSlug:"masterclass-commander",badge:"Best conversion value",guarantee:"30-day money-back guarantee",accentColor:"#D4AF37",deliveryMode:"download",positioning:"Best for builders who have something to sell but need a coherent conversion system rather than more disconnected tools."},
{slug:"masterclass-commander",name:"Scale & Licensing Commander",tier:"AutonomaX Masterclass",ladderTier:"masterclass",price:149,originalPrice:597,priceModel:"one_time",description:"Systemize a working commercial motion for repeatability: operating architecture, scale sprint, partnerships, automation controls, KPI diagnostics, and white-label usage rights.",bullets:["Master operating and revenue system map","White-label licensing guide and usage boundaries","60-Day Scale Sprint with milestones and experiments","Partnership Playbook with outreach templates","Automation OS schedules and failure-prevention controls","KPI dashboard with diagnostics and red flags","Golden Delivery Commander Pack ZIP"],checkoutUrl:CHECKOUT_SENTINEL,zipFilename:"AutonomaX_Masterclass_Commander_Pack_v2.zip",nextSlug:null,badge:"For repeatable scale",guarantee:"30-day money-back guarantee",accentColor:"#a78bfa",deliveryMode:"download",positioning:"Best after the offer and conversion path are understood and the next constraint is repeatability, partnerships, licensing, or operational scale."},
{slug:"revenue-audit-sprint",name:"Revenue Audit Sprint",tier:"AutonomaX Audit",ladderTier:"tripwire",price:29,originalPrice:97,priceModel:"one_time",description:"Focused review of a current stack, conversion path, and monetization options with structured recommendations.",bullets:["Technical stack and integration audit","Conversion tracking review","Ranked monetization opportunities","Written recommendations and next-action sequence"],checkoutUrl:"/contact?product=revenue-audit-sprint",zipFilename:null,nextSlug:"masterclass-pro",badge:"Request scope",accentColor:"#f59e0b",deliveryMode:"service",fulfillmentWindow:"Scope and delivery window confirmed before payment"}
];
export function getProduct(slug:string):Product|undefined{return products.find((p)=>p.slug===slug)}
export function getProductsByTier(tier:ProductTier):Product[]{return products.filter((p)=>p.ladderTier===tier)}
export function getPaidProducts():Product[]{return products.filter((p)=>p.priceModel!=="free")}
