'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, Loader2, Mail, ShieldCheck } from 'lucide-react';

export default function ContactFormTR(){
  const [status,setStatus]=useState<'idle'|'sending'|'done'|'error'>('idle'); const [error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending');setError('');const formElement=e.currentTarget;const form=new FormData(formElement);try{const res=await fetch('/api/lead',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:form.get('email'),name:form.get('name'),company:form.get('company'),interest:form.get('interest'),message:form.get('message'),desired_outcome:form.get('desired_outcome'),constraints:form.get('constraints'),slug:'tr-contact',source:'tr-contact-page'})});if(!res.ok){const data=await res.json().catch(()=>null);throw new Error(data?.error||'submit')}setStatus('done');formElement.reset()}catch{setError('Talep gönderilemedi. Bilgilerinizin kaybolmaması için metni kopyalayıp kagan@aikagan.com adresine gönderebilirsiniz.');setStatus('error')}}
  return <main className="min-h-screen bg-[#08080a] px-6 py-20 text-white"><section className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-emerald-300">İLETİŞİM VE UYGULAMA DESTEĞİ</p><h1 className="mt-3 max-w-3xl text-5xl font-black">İhtiyacınızı günlük dille anlatın.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-300">Teknik terim kullanmanız gerekmez. Ne yapmak istediğinizi, bugün neyin sizi durdurduğunu ve hangi sonucu beklediğinizi yazın.</p><div className="mt-10 grid gap-6 lg:grid-cols-[.7fr_1.3fr]">
    <aside className="space-y-4"><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-6"><Mail className="h-6 w-6 text-amber-300"/><h2 className="mt-4 text-xl font-black">Doğrudan e-posta</h2><a href="mailto:kagan@aikagan.com" className="mt-2 block text-amber-300">kagan@aikagan.com</a></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><ShieldCheck className="h-6 w-6 text-emerald-300"/><h2 className="mt-4 text-xl font-black">Gönderince ne olur?</h2><ol className="mt-3 space-y-3 text-sm leading-6 text-neutral-400"><li>1. Mesajınızı okuruz.</li><li>2. Anlamadığımız bir yer varsa size sorarız.</li><li>3. İş ücretliyse ne yapacağımızı, ne zaman biteceğini ve fiyatını size yazarız.</li><li>4. Siz onay vermeden ödeme almayız veya hesaplarınızda işlem yapmayız.</li></ol></div><Link href="/tr/outcome/intake" className="block rounded-2xl border border-sky-300/20 bg-sky-300/[.04] p-6"><strong className="text-sky-300">Önce ücretsiz taslak hazırlamak ister misiniz?</strong><span className="mt-2 block text-sm text-neutral-300">İş hedefi aracını açın →</span></Link></aside>
    <div className="rounded-3xl border border-white/10 bg-white/[.03] p-7">{status==='done'?<div className="py-12 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-300"/><h2 className="mt-5 text-3xl font-black">Talebiniz alındı.</h2><p className="mx-auto mt-3 max-w-md text-neutral-300">Mesajınızı kaydettik. İnceledikten sonra size yazacağız.</p><button onClick={()=>setStatus('idle')} className="mt-6 text-sm font-bold text-amber-300">Başka bir talep gönder</button></div>:<form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Adınız *" required placeholder="Örn. Ayşe Yılmaz"/><Field name="email" label="E-posta adresiniz *" type="email" required placeholder="siz@sirket.com"/></div><Field name="company" label="Şirket veya proje" placeholder="Varsa şirket/proje adı"/><label className="block text-sm text-neutral-300">Hangi konuda destek istiyorsunuz? *<select name="interest" required defaultValue="" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0b0e] px-4 py-3"><option value="" disabled>Bir seçenek seçin</option><option value="product-access">Satın aldığım dosyaya erişim</option><option value="revenue-review">Satış yolunun incelenmesi</option><option value="offer-setup">Teklif ve satış sayfası kurulumu</option><option value="automation">Tekrar eden işlerin otomasyonu</option><option value="other">Başka bir ihtiyaç</option></select></label><Area name="message" label="Bugünkü durumu anlatın *" required placeholder="Şu anda ne yapıyorsunuz, nerede zorlanıyorsunuz?"/><Area name="desired_outcome" label="Hangi sonucu almak istiyorsunuz? *" required placeholder="İş bittiğinde ne değişmiş olsun?"/><Area name="constraints" label="Bilmemiz gereken başka bir şey var mı?" placeholder="Örn. Bütçem 100 dolar. İş cuma günü bitsin. Mevcut ödeme sistemim değişmesin."/>{status==='error'?<p className="rounded-xl border border-red-300/25 bg-red-300/10 p-4 text-sm text-red-200">{error}</p>:null}<label className="flex items-start gap-3 text-sm leading-6 text-neutral-400"><input required type="checkbox" className="mt-1 h-4 w-4"/>Bu talebi göndermeye yetkiliyim. Şifre, kart bilgisi veya gizli erişim anahtarı paylaşmadım.</label><button disabled={status==='sending'} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3.5 font-black text-black disabled:opacity-60">{status==='sending'?<Loader2 className="h-4 w-4 animate-spin"/>:null}{status==='sending'?'Gönderiliyor…':'Talebimi gönder'}</button></form>}</div>
  </div></section></main>
}
function Field({name,label,type='text',required=false,placeholder}:{name:string;label:string;type?:string;required?:boolean;placeholder:string}){return <label className="block text-sm text-neutral-300">{label}<input name={name} type={type} required={required} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-amber-300"/></label>}
function Area({name,label,required=false,placeholder}:{name:string;label:string;required?:boolean;placeholder:string}){return <label className="block text-sm text-neutral-300">{label}<textarea name={name} rows={4} required={required} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-amber-300"/></label>}
