'use client';

import { FormEvent, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react';

type Draft = { stage:string; asset:string; priority:string; email:string; name:string; title:string; objective:string; boundary:string; baseline:string; target:string; owner:string; autonomy:string };
type Result = { missionId?:string; recommendedTier?:string; nextAction?:string };
const empty:Draft={stage:'',asset:'',priority:'',email:'',name:'',title:'',objective:'',boundary:'',baseline:'',target:'',owner:'',autonomy:'prepare'};
const choices=[
  {key:'stage',question:'Bugün hangi noktadasınız?',options:[['ideas','Fikirlerim var'],['offer','Satışa hazır bir ürün veya hizmetim var'],['operating','Faaliyette olan bir işletmem var']]},
  {key:'asset',question:'Elinizdeki en güçlü kaynak nedir?',options:[['skill','Uzmanlık veya mesleki beceri'],['audience','Çevre veya müşteri ağı'],['product','Ürün veya çalışan sistem'],['operations','İş kayıtları veya operasyon bilgisi']]},
  {key:'priority',question:'Şu anda en önemli sonuç nedir?',options:[['revenue','Daha hızlı gelir'],['reliability','Daha düzenli işleyiş'],['growth','Kontrollü büyüme']]},
] as const;
const autonomyNames:Record<string,string>={advise:'Yalnızca öneri sunabilir',prepare:'Onayınız için çalışma hazırlayabilir',approved:'Yalnızca onaylanan işlemi uygulayabilir'};
const tierNames:Record<string,string>={starter:'Başlangıç karar raporu',pro:'Gelir sistemi paketi',commander:'İşletme sistemi paketi'};

export default function OutcomeIntakeTR(){
  const [step,setStep]=useState(0); const [draft,setDraft]=useState<Draft>(empty); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<Result|null>(null);
  const route=useMemo(()=>choices.map(({key,options})=>options.find(([value])=>value===draft[key])?.[1]).filter(Boolean).join(' · '),[draft]);
  const update=(key:keyof Draft,value:string)=>setDraft(v=>({...v,[key]:value}));
  const clearMission=()=>setDraft(v=>({...v,title:'',objective:'',boundary:'',baseline:'',target:'',owner:'',autonomy:'prepare'}));
  const cancel=()=>{setDraft(empty);setStep(0);setResult(null);setError('Taslak silindi. Hiçbir bilgi gönderilmedi.');};
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const statement=[`Çalışma: ${draft.title}`,draft.objective,draft.boundary?`Korunacak sınır: ${draft.boundary}`:'',draft.baseline?`Mevcut durum: ${draft.baseline}`:'',draft.target?`Kabul ölçüsü: ${draft.target}`:'',draft.owner?`Sorumlu kişi: ${draft.owner}`:'',`Yapay zekâ yetkisi: ${autonomyNames[draft.autonomy]}`,`Başlangıç yolu: ${route}`].filter(Boolean).join('\n');try{const res=await fetch('/api/outcome/intake',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientEmail:draft.email,clientName:draft.name||draft.owner,bottleneckStatement:statement,path:draft.priority==='revenue'?'opportunity':draft.priority==='growth'?'manage':'build',tierInterest:'starter'})});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'submit');setResult({missionId:data?.mission?.missionId,recommendedTier:data?.mission?.recommendedTier,nextAction:data?.mission?.nextAction});}catch{setError('Taslak kaydedilemedi. Yazdıklarınız bu sayfada duruyor. Tekrar deneyin veya kagan@aikagan.com adresine yazın.');}finally{setBusy(false)}}
  if(result)return <main className="min-h-screen bg-[#07090d] px-6 py-16 text-white"><section className="mx-auto max-w-3xl rounded-3xl border border-emerald-300/25 bg-emerald-300/[.04] p-8"><CheckCircle2 className="h-10 w-10 text-emerald-300"/><p className="mt-6 text-sm font-black text-emerald-300">TASLAĞINIZ HAZIR</p><h1 className="mt-3 text-4xl font-black">İş hedefiniz kaydedildi.</h1><p className="mt-4 leading-7 text-neutral-300">Bu kayıt satın alma veya otomatik uygulama başlatmaz. İlk uygun yol: <strong className="text-white">{tierNames[result.recommendedTier||'starter']||'Başlangıç değerlendirmesi'}</strong>.</p>{result.missionId?<p className="mt-4 rounded-xl bg-black/25 p-4 text-sm text-neutral-300">Takip numarası: <strong className="text-white">{result.missionId}</strong></p>:null}{result.nextAction?<div className="mt-5 rounded-xl bg-black/25 p-4 text-sm leading-6 text-neutral-300"><strong className="text-white">Önerilen sonraki adım:</strong> Hedefinizi ve başarı ölçütünüzü gözden geçirin. Dilerseniz takip numaranızla uygulama desteği talep edin.</div>:null}<div className="mt-7 flex flex-wrap gap-3"><Link href="/tr/products" className="rounded-xl bg-amber-300 px-5 py-3 font-black text-black">Hazır paketleri gör</Link><Link href="/tr/contact" className="rounded-xl border border-white/15 px-5 py-3 font-bold">Uygulama desteği iste</Link><button onClick={()=>{setResult(null);setDraft(empty);setStep(0)}} className="rounded-xl border border-white/15 px-5 py-3 font-bold">Yeni taslak</button></div></section></main>;
  return <main className="min-h-screen bg-[#07090d] px-6 py-16 text-white"><section className="mx-auto max-w-4xl"><Link href="/tr/outcome" className="inline-flex items-center gap-2 text-sm font-bold text-sky-300"><ArrowLeft className="h-4 w-4"/>İş hedefi aracı</Link><div className="mt-8 flex items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.24em] text-amber-300">Yaklaşık 2 dakika</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Adım adım ilerleyin.</h1></div><span className="text-sm text-neutral-400">{step+1}/3</span></div><div className="mt-7 grid grid-cols-3 gap-2">{['Başlangıç','Hedef','Son kontrol'].map((x,i)=><div key={x} className={`rounded-full px-3 py-2 text-center text-xs font-bold ${i<=step?'bg-amber-300 text-black':'bg-white/5 text-neutral-500'}`}>{x}</div>)}</div>{error?<div className="mt-6 rounded-xl border border-amber-300/25 bg-amber-300/10 px-5 py-4 text-sm text-amber-100">{error}</div>:null}
    <form onSubmit={submit}>{step===0?<div className="mt-8 space-y-5">{choices.map(({key,question,options})=><fieldset key={key} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><legend className="px-2 text-lg font-bold">{question}</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{options.map(([value,label])=><button type="button" key={value} onClick={()=>update(key,value)} className={`rounded-xl border px-4 py-4 text-left font-semibold ${draft[key]===value?'border-amber-300 bg-amber-300/10':'border-white/10 bg-black/20 text-neutral-300'}`}>{label}{draft[key]===value?<CheckCircle2 className="ml-2 inline h-4 w-4 text-emerald-300"/>:null}</button>)}</div></fieldset>)}</div>:null}
    {step===1?<div className="mt-8 rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Adınız" value={draft.name} onChange={v=>update('name',v)} placeholder="Örn. Ayşe Yılmaz"/><Field label="İletişim e-posta adresiniz" type="email" value={draft.email} onChange={v=>update('email',v)} placeholder="siz@sirket.com"/></div><Field label="Çalışmanın kısa adı" required value={draft.title} onChange={v=>update('title',v)} placeholder="Örn. Yeni müşteriye dönüş süresini kısalt"/><Area label="Neyi değiştirmek veya başarmak istiyorsunuz?" required value={draft.objective} onChange={v=>update('objective',v)} placeholder="Örn. Gelen müşteri taleplerini tek yerde toplamak ve aynı gün yanıtlamak istiyorum."/><Area label="Hangi sınırlar korunmalı?" value={draft.boundary} onChange={v=>update('boundary',v)} placeholder="Örn. Müşteri verileri paylaşılmamalı; mevcut ödeme sistemi korunmalı."/><div className="grid gap-5 sm:grid-cols-2"><Field label="Bugünkü durum" value={draft.baseline} onChange={v=>update('baseline',v)} placeholder="Örn. Haftada 12 saat elle takip"/><Field label="Başarı ölçütünüz" required value={draft.target} onChange={v=>update('target',v)} placeholder="Örn. Yeni talep 5 dakikada sorumluya ulaşır"/></div><Field label="Onay verecek sorumlu kişi" required value={draft.owner} onChange={v=>update('owner',v)} placeholder="Ad veya görev"/><label className="mt-5 block text-sm font-bold text-neutral-200">Yapay zekâ ne yapabilir?<select value={draft.autonomy} onChange={e=>update('autonomy',e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#090d14] px-4 py-3"><option value="advise">Yalnızca öneri sunabilir</option><option value="prepare">İnsan onayı için çalışma hazırlayabilir</option><option value="approved">Yalnızca açıkça onaylanan işlemi uygulayabilir</option></select></label><div className="mt-7 flex flex-wrap gap-3"><button type="button" onClick={clearMission} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-sm font-bold"><Trash2 className="h-4 w-4"/>Hedef alanlarını temizle</button><button type="button" onClick={cancel} className="inline-flex items-center gap-2 rounded-xl border border-red-300/25 px-4 py-3 text-sm font-bold text-red-200"><RotateCcw className="h-4 w-4"/>Taslağın tamamını sil</button></div></div>:null}
    {step===2?<div className="mt-8 rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-8"><div className="flex gap-3"><ShieldCheck className="h-6 w-6 flex-none text-emerald-300"/><div><p className="text-xs font-black text-emerald-300">GÖNDERMEDEN ÖNCE KONTROL</p><h2 className="mt-2 text-2xl font-black">Bilgiler doğru mu?</h2><p className="mt-3 text-neutral-400">Göndermek ücretsiz bir görev taslağı oluşturur. Ödeme yapmaz, içerik yayımlamaz veya dış sistemlerde işlem başlatmaz.</p></div></div><dl className="mt-7 grid gap-4 sm:grid-cols-2">{[['Başlangıç yolu',route],['Çalışma',draft.title],['İstenen sonuç',draft.objective],['Başarı ölçüsü',draft.target],['Sorumlu kişi',draft.owner],['Yapay zekâ yetkisi',autonomyNames[draft.autonomy]]].map(([k,v])=><div key={k} className="rounded-xl bg-black/30 p-4"><dt className="text-xs font-bold text-neutral-500">{k}</dt><dd className="mt-2 whitespace-pre-wrap text-sm">{v||'Belirtilmedi'}</dd></div>)}</dl><label className="mt-7 flex gap-3 text-sm leading-6"><input required type="checkbox" className="mt-1 h-4 w-4"/>Bu hedefi incelemeye göndermeye yetkiliyim.</label></div>:null}
    <div className="mt-8 flex justify-between gap-4"><button type="button" disabled={step===0||busy} onClick={()=>setStep(v=>v-1)} className="rounded-xl border border-white/15 px-5 py-3 font-bold disabled:opacity-30">Geri</button>{step<2?<button type="button" disabled={step===0&&!(draft.stage&&draft.asset&&draft.priority)} onClick={(e)=>{if(step===0||e.currentTarget.form?.reportValidity())setStep(v=>v+1)}} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3 font-black text-black disabled:opacity-40">Devam <ArrowRight className="h-4 w-4"/></button>:<button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-6 py-3 font-black text-black">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:null}Onayla ve sonucu hazırla</button>}</div></form><p className="mt-8 text-center text-xs text-neutral-500">Destek ve gizlilik: kagan@aikagan.com</p></section></main>;
}

function Field({label,value,onChange,type='text',required=false,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;placeholder?:string}){return <label className="mt-5 block text-sm font-bold text-neutral-200">{label}<input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-amber-300"/></label>}
function Area({label,value,onChange,required=false,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;placeholder?:string}){return <label className="mt-5 block text-sm font-bold text-neutral-200">{label}<textarea rows={4} required={required} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-amber-300"/></label>}

